### ISSUE TITLE
Application freezes V3.3

### ISSUE THREAD

**Issue by Latzen** [stellarchat/desktop-client#178] opened 2018-01-07 14:49 UTC
Freeze when trying to show password or secret key. Steps to reproduce:

1. Create new account
2. Select target file
3. Enter password
4. Click: Show password or secret key
5. Application freez
![image](https://user-images.githubusercontent.com/5215432/34650472-171966f6-f3c2-11e7-830c-886bb6a726c0.png)

OS: Windows 10 b. 1703

**Comment by copa017** [comment] 2018-01-08 21:01
Duplicate of [this](https://github.com/stellarchat/desktop-client/issues/164)

**Comment by naifamoodi** [comment] 2018-01-21 12:14
Its been a month since this problem was first reported on https://github.com/stellarchat/desktop-client/issues/164

I can confirm that the problem still persists.

I am using 64 bit version on W10. I also tried using the 32 bit version but its the same with that one also.

I hope this gets resolved soon.

**Comment by stellarchat** [comment] 2018-02-16 12:56
fixed in v3.5

**Closed by stellarchat** 2018-02-16 12:56 UTC
